# Generated by Django 2.2.8 on 2020-05-19 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200519_1334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserActivity',
            new_name='Login',
        ),
        migrations.CreateModel(
            name='Logout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logout_time', models.DateTimeField()),
                ('usern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.User')),
            ],
        ),
    ]
