# Generated by Django 2.2.8 on 2020-05-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200519_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='logout_time',
        ),
    ]
