# Generated by Django 2.2.8 on 2020-05-19 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200519_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logout',
            name='usern',
        ),
        migrations.AddField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 18, 30, 41, 136431)),
        ),
        migrations.AddField(
            model_name='user',
            name='logout_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 18, 30, 41, 136431)),
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Logout',
        ),
    ]
